export const SET_LOADING = 'ToDo/SET_LOADING';

export const GET_TODOS = 'ToDo/GET_TODOS';
export const GET_TODOS_REQUESTED = 'ToDo/GET_TODOS_REQUESTED';

export const SET_TODO_TITLE = 'ToDo/SET_TODO_TITLE';
export const SET_TODO_TITLE_REQUESTED = 'ToDo/SET_TODO_TITLE_REQUESTED';

export const CLEAR_TODO_TITLE = 'ToDo/CLEAR_TODO_TITLE';

export const CREATE_TODO = 'ToDo/CREATE_TODO';
export const CREATE_TODO_REQUESTED = 'ToDo/CREATE_TODO_REQUESTED';

export const DELETE_TODO = 'ToDo/DELETE_TODO';
export const DELETE_TODO_REQUESTED = 'ToDo/DELETE_TODO_REQUESTED';
